### ISSUE TITLE
Why linear layers used in the model?

### ISSUE THREAD

**Issue by DeVriesMatt** [black0017/3D-GAN-pytorch#2]
Hi,

Great repo! 

I just wanted to ask why you used linear layers in the models? The paper explains that their model is "all convolutional" and that they included "no pooling or linear layers in our network". I'm reimplementing their paper with the same strategy and cannot obtain similar results. Only when I incorporate linear layers, does the model converge.

**Comment by black0017** [comment]
Hello,

First you need a linear model in the generator to convert the 200-dim vector to the initial mini-volume (4x4x4) (here)[
https://github.com/black0017/3D-GAN-pytorch/blob/master/models/GAN3D.py#L78]

Then you need another linear layer (or maybe a conv that outputs a scalar ) in the discriminator to get a single scalar output in the range [0,1] due to sigmoid. 

https://github.com/black0017/3D-GAN-pytorch/blob/master/models/GAN3D.py#L53

By looking by at the paper appendix: 
![image](https://user-images.githubusercontent.com/13345132/122192101-9f1e2780-ce93-11eb-9708-b6925dca4718.png)

Maybe we can add a 5th 3d conv with kernel of 4 and stride of 1. If the output of the conv is not a scalar we would eventually need to flatten + add a linear layer + sigmoid . 

"no pooling or linear layers in our network" is not including the input output layers - probably for marketing purposes :P . they basically extended the idea of dcgan to 3d
